name: Triggers

# This step triggers after TBD-step-5-event-desc
# This step sets STEP to X
# This step closes <details id=5> and opens <details id=X>

# This will run every time we TBD-step-5-event-desc
# Reference https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
    inputs:
      lenguaje_favorito:
        description: "Lenguaje favorito"
        default: JavaScript
        required: true
        type: choice
        options:
          - Python
          - JavaScript
          - Go
      nombre:
        description: "Mi nombre"
        required: true
        default: Edwin
        type: string

  push:
    branches:
      - aprendiendo-github-actions

permissions:
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to update the step metadata
  contents: write

jobs:
  hola-mundo-manual:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Instalar Node.js
        uses: actions/setup-node@v6.3.0
        with:
          node-version: 22

      - name: Instalar Typescript y tipos de Node
        run: npm install --save-dev typescript @types/node

      - name: Definir nombre
        run: echo "USERNAME=${{ inputs.nombre }}" >> $GITHUB_ENV

      - name: Definir lenguaje
        run: echo "LANGUAGE=${{ inputs.lenguaje_favorito }}" >> $GITHUB_ENV

      - name: Compilar typescript
        run: tsc

      - name: Correr script
        run: node dist/lenguaje-favorito.js
